# Copyright (C) 2018 Kamax Sàrl
# https://www.kamax.io/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

swagger: '2.0'
info:
  title: "Matrix Identity Service Session API"
  version: "1.0.0"
host: localhost:8090
schemes:
  - https
basePath: /_matrix/identity/api/v1
produces:
  - application/json
paths:
  "/validate/email/requestToken":
    post:
      summary: Creates an email 3PID session and initiates the validation procedure.
      description: |
        Creates an email 3PID session which can be used to validate ownership of
        the given 3PID and later bind it to a Matrix ID.

        The Identity server will send a token to the given email address.  
        The token can then be provided to the appropriate token submission endpoint.
      operationId: sessionEmailRequestToken
      parameters:
        - in: body
          name: body
          schema:
            type: object
            example: {
              client_secret: "TopSecretString",
              email: "john.doe@example.org",
              send_attempt: 1
            }
            properties:
              client_secret:
                type: string
                title: Client secret
                description: The client secret that will be used when performing actions on the session.
              send_attempt:
                type: integer
                title: Send attempt
                description: |
                  Uniquely identify this token request.
                  If a new request is needed (e.g. reminder), this should be incremented.
              next_link:
                type: string
                title: Next link
                description: URL to redirect the client to after validation is complete.
              email:
                type: string
                title: Email address
                description: The email address to validate and to which the token should be sent.
            required:
              - "client_secret"
              - "email"
      responses:
        200:
          description: The session was successfully created and the token was communicated.
          examples:
            application/json: {
                "sid": "M3BpZFNlc3Npb25JZEV4YW1wbGUK"
            }
          schema:
            type: object
            properties:
              sid:
                type: string
                description: The ID of the session that was created.
            required:
              - "sid"
        501:
          description: The Identity service does not have the capability to validate the 3PID medium type.
  "/validate/msisdn/requestToken":
    post:
      summary: Create a phone number 3PID session and initiate the validation procedure.
      description: |
        Create a phone number 3PID session which can be used to validate ownership of the given 3PID and later bind it to a Matrix ID.

        A token is sent to the given phone number that can be provided to the appropriate token submission endpoint.
      operationId: sessionMsisdnRequestToken
      parameters:
        - in: body
          name: body
          schema:
            type: object
            example: {
              client_secret: "TopSecretString",
              country: "be",
              phone_number: "0495/01.23.45",
              send_attempt: 1
            }
            properties:
              client_secret:
                type: string
                title: Client secret
                description: The client secret that will be used when performing actions on the session.
              send_attempt:
                type: integer
                title: Send attempt
                description: Uniquely identify this token request. If a new request is needed (reminder), this should be incremented.
              next_link:
                type: string
                title: Next link
                description: URL to redirect the client to after validation is complete.
              country:
                type: string
                title: Country code
                description: |-
                  The 2-letter country code to use to build a msisdn 3PID in
                  case the phone number is not an international format.
                  
                  If the phone number is in international format, this value
                  will be ignored and can be empty.
              phone_number:
                type: string
                title: Phone number
                description: The national or international phone number to parse and format as msisdn.
            required:
              - "client_secret"
              - "country"
              - "phone_number"
      responses:
        200:
          description: The session was successfully created and the token was communicated.
          examples:
            application/json: {
                "sid": "M3BpZFNlc3Npb25JZEV4YW1wbGUK",
                "msisdn": "32495012345"
            }
          schema:
            type: object
            properties:
              sid:
                type: string
                description: The ID of the session that was created.
              msisdn:
                type: string
                description: The canonical address for this phone number in MSISDN format.
            required:
              - "sid"
        501:
          description: The Identity service does not have the capability to validate the 3PID medium type.
