# Copyright (C) 2018 Kamax Sàrl
# https://www.kamax.io/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

swagger: '2.0'
info:
  title: "Matrix Identity Service Session API"
  version: "1.0.0"
host: localhost:8090
schemes:
  - https
basePath: /_matrix/identity/api/v1
produces:
  - application/json
paths:
  "/3pid/getValidated3pid":
    post:
      summary: Gets the validated 3PID for the session.
      description: |
        Gets the validated 3PID for the session, if the session has been validated.

        If the session has not yet been validated, an error is returned.
      operationId: threepidCheckValidated
      parameters:
        - in: query
          name: sid
          type: string
          required: true
          description: The session ID returned by the ``requestToken`` endpoint.
        - in: query
          name: client_secret
          required: true
          type: string
          description: The client secret provided to the ``requestToken`` endpoint.
      responses:
        200:
          description: The validation information for this session.
          examples:
            application/json: {
              "medium": "email",
              "address": "john.doe@example.org",
              "validated_at": 1457622739026
            }
          schema:
            type: object
            properties:
              medium:
                type: string
                description: The medium type of the 3PID.
              address:
                type: string
                description: The canonical address of the 3PID.
              validated_at:
                type: integer
                description: Epoch millisecond timestamp when the 3PID address was validated.
            required:
              - "medium"
              - "address"
              - "validated_at"
        401:
          description: The session has not yet been validated.
          examples:
            application/json: {
              "errcode": "M_SESSION_NOT_VALIDATED",
              "error": "This validation session has not yet been completed"
            }
        403:
          description: The session credentials provided are not valid.
