# Copyright (C) 2018 Kamax Sàrl
# https://www.kamax.io/
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>

swagger: '2.0'
info:
  title: "Matrix Federation Get State API"
  version: "1.0.0"
host: localhost:8448
schemes:
  - https
basePath: /_matrix/federation/v1
produces:
  - application/json
paths:
  "/state/{roomId}":
    get:
      summary: Gets room state for a specific event.
      description: Gets room state for a specific event.
      operationId: getStateForEventInRoom
      parameters:
        - in: path
          name: roomId
          type: string
          description: The room ID of the event referenced in query parameters.
          example: "!roomid:example.org"
        - in: query
          name: event_id
          type: string
          description: The event ID for which we want the state.
          example: "$eventid:example.org"
      responses:
        200:
          description: |
            The room state for that event, including the authentication chain
            for the state.
          examples:
            application/json: {
              "auth_chain": [
                {
                  "**UNKNOWN**": "**UNKNOWN**"
                },
                {
                  "**UNKNOWN**": "**UNKNOWN**"
                }
              ],
              "pdus": [
                {
                  "**UNKNOWN**": "**UNKNOWN**"
                },
                {
                  "**UNKNOWN**": "**UNKNOWN**"
                }
              ]
            }
          schema:
            type: object
            properties:
              auth_chain:
                type: array
                description: Authentication chain that validate the PDUs.
                items:
                  type: object
                  title: PDUs
              pdus:
                type: array
                description: Events that make up the state.
                items:
                  type: object
                  title: PDUs
            required:
              - "auth_chain"
              - "pdus"
  "/state_ids/{roomId}":
    get:
      summary: Get room state's event IDs for a specific event.
      description: Get room state's event IDs for a specific event.
      operationId: getStateIdsForEventInRoom
      parameters:
        - in: path
          name: roomId
          type: string
          required: true
          description: The room ID of the event referenced in query parameters.
          example: "!roomid:example.org"
        - in: query
          name: event_id
          type: string
          required: true
          description: The event ID for which we want the state.
          example: "$eventid:example.org"
      responses:
        200:
          description: |
            The room state for that event, including the authentication chain
            for the state.
          examples:
            application/json: {
              "auth_chain_ids": [
                "!authChainEventId1:example.org",
                "!authChainEventId2:example.org"
              ],
              "pdu_ids": [
                "!pduId1:example.org",
                "!pduId2:example.org"
              ],
            }
          schema:
            type: object
            properties:
              auth_chain_ids:
                type: array
                description: Event IDs of the PDUs' authentication chain.
                items:
                  type: string
              pdu_ids:
                type: array
                description: Event IDs that make up the state.
                items:
                  type: string
                  title: PDUs
            required:
              - "auth_chain_ids"
              - "pdu_ids"
